apiVersion: v1
kind: Namespace
metadata:
  name: django-chat
  labels:
    name: django-chat
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: django-chat-dev
  labels:
    name: django-chat-dev
    environment: development
